name: Feature request
labels: [ "enhancement" ]
description: Suggest an idea or general improvement
assignees: [ "jonathanlukas" ]
title: Feature request
body:
- type: textarea
  id: describe-the-problem
  attributes:
    label: Is your feature request related to a problem? Please describe.
    description: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    placeholder: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
  validations:
    required: true
- type: textarea
  id: desired-solution
  attributes:
    label: Describe the solution you'd like
    description: A clear and concise description of what you want to happen
    placeholder: A clear and concise description of what you want to happen
  validations:
    required: true
- type: textarea
  id: alternatives
  attributes:
    label: Describe alternatives you've considered
    description: A clear and concise description of any alternative solutions or features you've considered
    placeholder: A clear and concise description of any alternative solutions or features you've considered
  validations:
    required: true
- type: textarea
  id: additional-context
  attributes:
    label: Additional context
    description: Add any other context or screenshots about the feature request here
    placeholder: Add any other context or screenshots about the feature request here
  validations:
    required: true