name: Task
labels: [ "task" ]
description: Describe a generic activity we should carry out
assignees: [ "jonathanlukas" ]
title: Task
body:
- type: textarea
  id: what
  attributes:
    label: What should we do?
    description: Clearly describe the activity we should carry out
    placeholder: Clearly describe the activity we should carry out
  validations:
    required: true
- type: textarea
  id: why
  attributes:
    label: Why should we do it?
    description: Argue why doing it is a healthy investment of our time
    placeholder: Argue why doing it is a healthy investment of our time
  validations:
    required: true